config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'marcas/index'

  resources:marcas

  resources:productos
  
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/marca.rb
class Marca < ApplicationRecord
  #se establece como campo requerido
  validates :nombre, presence: true
end

app/models/producto.rb
class Producto < ApplicationRecord
  validates_presence_of :nombre, :message => "Campo requerido."
  validates_presence_of :marca, :message => "Campo requerido."
  validates :precio, :numericality => { greater_than: 1, less_than_or_equal_to: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
  def index
    @marcas = Marca.all
  end
  
  def new
    @marca = Marca.new
  end
  
  def edit
    @marca = Marca.find(params[:id])
  end
  
  def create
    @marca = Marca.new(marca_params)
    #Si la marca no fue guardada redirecciona al formulario
    if @marca.save
      redirect_to @marca
    else
      render 'new'
    end
  end
  
  def update
    @marca = Marca.find(params[:id]) 
    if @marca.update(marca_params)
      redirect_to @marca
    else
      render 'edit'
    end
  end
  private def marca_params
    params.require(:marca).permit(:nombre)
  end

  def show
    @marca = Marca.find(params[:id])
  end
  
  def destroy
  @marca = Marca.find(params[:id])
  @marca.destroy 
  redirect_to marcas_path
end
end
 

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  def index
    @productos = Producto.all
  end
  
  def new
    @producto = Producto.new
  end
  
  def edit
    @producto = Producto.find(params[:id])
  end
  
  def create
    @producto = Producto.new(producto_params)
    #Si el producto no fue guardado redirecciona al formulario
    if @producto.save
      redirect_to @producto
    else
      render 'new'
    end
  end
  
  def update
    @producto = Producto.find(params[:id]) 
    if @producto.update(producto_params)
      redirect_to @producto
    else
      render 'edit'
    end
  end
  private def producto_params
    params.require(:producto).permit(:nombre, :marca, :descripcion, :precio)
  end

  def show
    @producto = Producto.find(params[:id])
  end
  
  def destroy
  @producto = Producto.find(params[:id])
  @producto.destroy 
  redirect_to productos_path
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFirstApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/marcas/_form.html.erb
<%= bootstrap_form_for @marca do |m| %>
  <% if @marca.errors.any? %>
    <div id="error_explanation">
        <p><strong>El registro no fue guardado.</strong></p>
        <ul>
            <% @marca.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
  <% end %>
  <p>
      <%= m.text_field :nombre %>
  </p> 
  <p>
      
      <%= m.submit 'Guardar', class: 'btn btn-success'%>
  </p>
<% end %>
  <br>
<%= link_to  marcas_path do %>
  <i class="fa fa-arrow-left"></i> Regresar
<% end %>

app/views/marcas/edit.html.erb
<div class="container">
<h2>Editar marca</h2>
<hr>
<!--Muestra el formulario que se encuentra en la vista-->
<div class="col-lg-6">
<%= render 'form' %>
</div>
</div>

app/views/marcas/index.html.erb
<div class="container">
    <h1>Lista de marcas</h1>

    <%= link_to new_marca_path, class: "btn btn-info" do %>
        <i class="fa fa-plus-circle"></i> Nueva marca
      <% end %>
     
      <br>
      <table class="table table-striped">
          <thead>
              <tr>
                  <th>Nombre</th>
                  <th colspan="3">Acciones</th>
              </tr>
          </thead>
          <tbody>
              <% @marcas.each do |marca| %>
                <tr>
                    <td><%= marca.nombre %></td>
                    <td>
                        <%= link_to marca_path(marca), title: "Ver" do %>
                          <span class="fa fa-eye"></span>
                        <% end %>
                        &nbsp;
                        <%= link_to edit_marca_path(marca), title: "Editar" do %>
                          <span class="fa fa-pencil"></span>
                        <% end %>
                        &nbsp; 
                        <%= link_to marca_path(marca), title: "Eliminar",
                          method: :delete,
                          data:{confirm: '¿Esta seguro que quiere eliminar el registro'} do%>
                        <span class="fa fa-trash"></span>
                      <% end %>
                  </td>
              </tr>
              <% end %>
          </tbody>        
    </table>
    <br>

    <%= link_to controller: 'welcome' do %>
        <i class="fa fa-arrow-left"></i> Home
      <% end %>
</div>

app/views/marcas/new.html.erb
<div class="container">
<h3>Nueva marca</h3>
<hr>
<div class="col-lg-6">
<%= render 'form' %>
</div>
</div>

app/views/marcas/show.html.erb
<div class="container">
<h2>Marca</h2>
<hr>
<p>
  <strong>Nombre:</strong>
  <%= @marca.nombre %>
</p>
<br>
<%= link_to  marcas_path do %>
  <i class="fa fa-arrow-left"></i> Regresar
<% end %>
</div>

app/views/productos/_form.html.erb
<%= bootstrap_form_for @producto do |p| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            <strong>El registro no fue guardado</strong>
            <ul>
                <% @producto.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
  <% end %>
  <%= p.text_field :nombre %>
  <%= p.text_field :descripcion %>
  <%= p.collection_select :marca, Marca.all, :id, :nombre, :prompt => "Seleccione una marca" %>
  <%= p.text_field :precio %>
  <%= p.submit 'Guardar', class: 'btn btn-success' %>
  <% end %>
  <br>
  <%= link_to  productos_path do %>
    <i class="fa fa-arrow-left"></i> Regresar
  <% end %>

app/views/productos/edit.html.erb
<div class="container">
<h2>Editar producto</h2>
<hr>
<!--Muestra el formulario que se encuentra en la vista-->
<div class="col-lg-6">
<%= render 'form' %>
</div>
</div>

app/views/productos/index.html.erb
<div class="container">
    <h1>Lista de productos</h1>
    <hr>
    <%= link_to new_producto_path, class: "btn btn-info" do %>
        <i class="fa fa-plus-circle"></i> Nuevo producto
      <% end %>

      <br>
      <table class="table table-striped">
          <thead>
              <tr>
                  <th>Nombre</th>
                  <th>Marca</th>
                  <th>Descripción</th>
                  <th>precio</th>
                  <th>Acciones</th>
              </tr>
          </thead>
          <tbody>
              <% @productos.each do |producto| %>
                <tr>
                    <td><%= producto.nombre %></td>
                    <td><%= producto.marca %></td>
                    <td><%= producto.descripcion %></td>
                    <td>$<%= producto.precio %></td>
                    <td><%= link_to producto_path(producto), title: "Ver producto" do %>
                          <span class="fa fa-eye"></span>
                        <% end %>
                        &nbsp;
                        <%= link_to edit_producto_path(producto), title: "Editar producto" do %>
                          <span class="fa fa-pencil"></span>
                        <% end %>
                        &nbsp; 
                        <%= link_to producto_path(producto), title: "Eliminar producto",
                          method: :delete,
                          data:{confirm: '¿Esta seguro que quiere eliminar el producto'} do%>
                          <span class="fa fa-trash"></span>
                        <%end%>
                    </td>
                </tr>
              <% end %>
          </tbody>
      </table>
      <br>
      <%= link_to controller: 'welcome' do %>
        <i class="fa fa-arrow-left"></i> Home
      <% end %>
  </div>

app/views/productos/new.html.erb
<div class="container">
    <h1>Nuevo producto</h1>
    <hr>
    <div class="col-lg-6 col-md-6">
        <%= render 'form' %>
    </div>

</div>

app/views/productos/show.html.erb
<div class="container">
<h2>Producto</h2>
<hr>
<p>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</p>
<p>
  <strong>Marca:</strong>
  <%= @producto.marca %>
</p>
<p>
  <strong>Descripción:</strong>
  <%= @producto.descripcion %>
</p>
<p>
  <strong>Precio:</strong>
  $<%= @producto.precio %>
</p>
<br>
<%= link_to  productos_path do %>
  <i class="fa fa-arrow-left"></i> Regresar
<% end %>
</div>

app/views/welcome/index.html.erb
<div class="container">
    <h1>Bienvenido</h1>
    <h3>A mi primer aplicación en Ruby on Rails</h3>
    <hr>
    <p>Selecciona un CRUD</p>
    <%= link_to new_marca_path, class: "btn btn-info" do %>
        <i class="fa fa-tags"></i> Marcas
      <% end %>
        <%= link_to new_producto_path, class: "btn btn-info" do %>
        <i class="fa fa-shopping-cart"></i> Productos
      <% end %>
</div>
<footer class="footer navbar-fixed-bottom">
      <div class="container">
        <p class="text-muted">&copy;2017 Rosario Guadalupe Luis Rodríguez</p>
      </div>
    </footer>